spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to EmiBank loans related prod APIs "
  contactDetails:
    name: "Andreas Olsson - Product Owner"
    email: "andreas@emibank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384