spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "10.0"

loans:
  message: "Welcome to EmiBank loans related QA APIs "
  contactDetails:
    name: "Anna Ahl - QA Lead"
    email: "anna@emibank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371